
spring:
  application:
    name: cliente-api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      username: sa
      password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher